### ISSUE TITLE
tyrion -e should not look at the `master` git reference

### ISSUE THREAD

**Issue by MickaelBergem** [theodo/tyrion#44]
I'm trying to have Tyrion generate the evolution report on our internal Jenkins, but Jenkins doesn't checkout the `master` branch locally. Tyrion needs to read the `master` branch to compute the evolution, so it does not work.

Would it be possible to just look at the current HEAD and inspect the parent commits?
Running `git log` works fine from inside Jenkins. Or at least to have an option / flag to generate the report from the current commit instead of latest master (even though they might be the same).

**Comment by MaximeThoonsen** [comment]
Hi @MickaelBergem , 
I'm using https://www.nodegit.org/api/commit/#history to walk through the history. I need to checkout every relevant commit in order to parse them. I'll investigate more later but I'm not sure we can do it using nodegit.
One potential solution is to save somewhere the result of the previous scans but it's far more complex than the current solution.

I'm curious about why can't you checkout master ?
