### ISSUE TITLE
ScanPath is used to search for custom .tyrion-config.json files

### ISSUE THREAD

**Issue by mbagur** [theodo/tyrion#88]
When using the `-p` argument to scan a specific directory of the project. The `.tyrion-config.json` file is searched in this directory. Which makes it impossible to have a config file for the project and allow to scan different folders.

For example, I have `.tyrion-config.json` file at the root of my project and I want to scan `src/` it will look for `src/.tyrion-config.json`

The custom config file could be searched in the folder where the command is executed or the executable could have a parameter to give the config path.

I'll gladly open a PR for any of these solutions if you want

**Comment by MaximeThoonsen** [comment]
Hello @mbagur,
Just to understand your problem correctly: why do you use -p to scan a subfolder? It's one of the use case but I want to be sure to understand all usage :).
Are you in France? Would it be possible to call you so you can explain me? If yes let's exchange by mail: maximet at theodo.fr

To keep it simple: we could say that Tyrion looks for a config in the `src/` folder. If there is one, it takes it otherwise it take the config from where the command is executed and if there is none it takes the default. 
Would that be ok for your?

**Comment by MaximeThoonsen** [comment]
@mbagur the new version with the fix has been pushed to npm
